name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.14.0]  # Include Node.js version 20.14.0

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies and rebuild native addons
      run: |
        npm install
        npm rebuild gl  # Rebuild native addon 'gl'

    - name: Install ffmpeg-concat
      run: npm install --save ffmpeg-concat

    - name: Run tests
      run: npm test

    - name: Package build artifacts
      if: success()
      run: tar -czf artifacts.tar.gz node_modules

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: artifacts.tar.gz
